name: qscan
description: A QR code scanner and creator app with 6 comprehensive screens.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Icons
  cupertino_icons: ^1.0.6
  
  # QR Code Functionality
  mobile_scanner: ^3.5.6
  qr_flutter: ^4.1.0
  google_mlkit_barcode_scanning: ^0.10.0
  
  # Camera and Permissions
  permission_handler: ^11.3.1
  
  # Image and File Handling
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  gal: ^2.2.0
  
  # Storage and Data
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  
  # Utilities
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  
  # State Management (optional)
  provider: ^6.1.1
  
  # Network and HTTP
  http: ^1.2.1
  
  # Date and Time
  intl: ^0.19.0
  
  # UI Enhancements
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1   # <-- added for app icons

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/
  
  # Fonts (optional - using system fonts for now)
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: fonts/SFProDisplay-Regular.ttf
  #       - asset: fonts/SFProDisplay-Medium.ttf
  #         weight: 500
  #       - asset: fonts/SFProDisplay-Bold.ttf
  #         weight: 700

# Platform-specific configurations
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#ffffff"

# App icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
